const List<String> cirurgias = [
  'Apendicectomia',
  'Colecistectomia',
  'Histerectomia',
  'Cesárea',
  'Mastectomia',
  'Prostatectomia',
  'Artroplastia de quadril',
  'Artroplastia de joelho',
  'Revascularização do miocárdio (cirurgia de ponte de safena)',
  'Cirurgia de catarata',
  'Cirurgia de desvio gástrico',
  'Laqueadura',
  'Vasectomia',
  'Amigdalectomia',
  'Adenoidectomia',
  'Cirurgia de hérnia',
  'Cirurgia bariátrica',
  'Lobectomia pulmonar',
  'Ressecção de tumor cerebral',
  'Cirurgia de descompressão da coluna',
  'Cirurgia de prótese de disco intervertebral',
  'Cirurgia de aneurisma da aorta',
  'Septoplastia',
  'Rinoplastia',
  'Blefaroplastia',
  'Otoplastia',
  'Abdominoplastia',
  'Lipoaspiração',
  'Mamoplastia de aumento',
  'Mamoplastia redutora',
  'Transplante de fígado',
  'Transplante de coração',
  'Transplante de rim',
  'Cirurgia de reparo de válvula cardíaca',
  'Cirurgia de stent coronário',
  'Cirurgia de fusão espinhal',
  'Artroscopia de joelho',
  'Artroscopia de ombro',
  'Craniotomia',
  'Hemorroidectomia',
  'Cirurgia de cisto pilonidal',
  'Cirurgia de câncer de mama',
  'Cirurgia de câncer de próstata',
  'Cirurgia de câncer de colo de útero',
  'Cirurgia de câncer de pulmão',
  'Cirurgia de câncer de estômago',
  'Cirurgia de câncer de esôfago',
  'Cirurgia de câncer de pâncreas',
  'Cirurgia de câncer de fígado',
  'Cirurgia de câncer de intestino',
  'Cirurgia de câncer de rim',
  'Cirurgia de câncer de bexiga',
  'Cirurgia de câncer de tireoide',
  'Cirurgia de câncer de boca',
  'Cirurgia de câncer de laringe',
  'Cirurgia de câncer de faringe',
  'Cirurgia de câncer de pele',
  'Cirurgia de câncer de ovário',
  'Cirurgia de câncer de endométrio',
  'Cirurgia de câncer de testículo',
  'Cirurgia de melanoma',
  'Cirurgia de ginecomastia',
  'Cirurgia de lábio leporino',
  'Cirurgia de palato fendido',
  'Orquiectomia',
  'Salpingo-ooforectomia',
  'Cistectomia',
  'Proctocolectomia',
  'Pancreatectomia',
  'Gastrectomia',
  'Duodenopancreatectomia',
  'Esplenectomia',
  'Cirurgia de fratura óssea',
  'Cirurgia de correção de escoliose',
  'Cirurgia de remoção de cálculo renal',
  'Cirurgia de cisto ovariano',
  'Cirurgia de endometriose',
  'Cirurgia de varizes',
  'Flebectomia',
  'Cirurgia de estenose carotídea',
  'Cirurgia de reparo de tendão',
  'Cirurgia de reparo de nervo',
  'Cirurgia de reparo de ligamento',
  'Cirurgia de redução de fratura',
  'Cirurgia de reparo de válvula mitral',
  'Cirurgia de reparo de válvula aórtica',
  'Cirurgia de reparo de válvula tricúspide',
  'Cirurgia de reparo de válvula pulmonar',
  'Toracotomia',
  'Laringectomia',
  'Laminectomia',
  'Cirurgia de redução mamária',
  'Cirurgia de aumento mamário',
  'Cirurgia de explante de prótese mamária',
  'Cirurgia de retirada de corpo estranho',
  'Cirurgia de quisto sebáceo',
  'Cirurgia de quisto sinovial',
  'Cirurgia de quisto de Baker',
  'Cirurgia de túnel do carpo',
  'Cirurgia de contratura de Dupuytren',
  'Cirurgia de síndrome de Quervain',
  'Cirurgia de fratura de punho',
  'Cirurgia de fratura de fêmur',
  'Cirurgia de fratura de tornozelo',
  'Cirurgia de fratura de coluna',
  'Cirurgia de fratura de clavícula',
  'Cirurgia de fratura de omoplata',
  'Cirurgia de fratura de costela',
  'Cirurgia de fratura de pelve',
  'Cirurgia de fratura de mandíbula',
  'Cirurgia de fratura de crânio',
  'Cirurgia de correção de pé torto',
  'Cirurgia de correção de joanete',
  'Cirurgia de correção de dedo em martelo',
  'Cirurgia de correção de sindactilia',
  'Cirurgia de correção de polidactilia',
  'Cirurgia de remoção de lipoma',
  'Cirurgia de remoção de nódulo mamário',
  'Cirurgia de remoção de pólipo intestinal',
  'Cirurgia de remoção de pólipo nasal',
  'Cirurgia de remoção de pólipo uterino',
  'Cirurgia de remoção de pólipo vesical',
  'Cirurgia de remoção de pólipo vocal',
  'Cirurgia de remoção de pólipo gástrico',
  'Cirurgia de cisto de Bartolin',
  'Cirurgia de cisto tireoglosso',
  'Cirurgia de cisto branquial',
  'Cirurgia de cisto poplíteo',
  'Cirurgia de cisto de Naboth',
  'Cirurgia de cisto dentígero',
  'Cirurgia de cisto maxilar',
  'Cirurgia de cisto mandibular',
  'Cirurgia de cisto sebáceo',
  'Cirurgia de cisto pilonidal',
  'Cirurgia de cisto mucoso',
  'Cirurgia de cisto sinovial',
  'Cirurgia de cisto ovariano',
  'Cirurgia de cisto renal',
  'Cirurgia de cisto hepático',
  'Cirurgia de cisto pancreático',
  'Cirurgia de cisto mesentérico',
  'Cirurgia de cisto pleural',
  'Cirurgia de cisto pericárdico',
  'Cirurgia de cisto peritoneal',
  'Cirurgia de cisto aracnoide',
  'Cirurgia de cisto dermoide',
  'Cirurgia de cisto sebáceo',
  'Cirurgia de cisto epidermoide',
  'Cirurgia de cisto tireóide',
  'Cirurgia de cisto timético'

];

const List<String> consultas = [
  'Consulta clínica geral',
  'Consulta pediátrica',
  'Consulta ginecológica',
  'Consulta obstétrica',
  'Consulta cardiológica',
  'Consulta ortopédica',
  'Consulta dermatológica',
  'Consulta neurológica',
  'Consulta psiquiátrica',
  'Consulta psicológica',
  'Consulta oftalmológica',
  'Consulta otorrinolaringológica',
  'Consulta endocrinológica',
  'Consulta nefrológica',
  'Consulta urológica',
  'Consulta gastroenterológica',
  'Consulta pneumológica',
  'Consulta reumatológica',
  'Consulta geriátrica',
  'Consulta de medicina esportiva',
  'Consulta de medicina preventiva',
  'Consulta de nutrição',
  'Consulta de fisioterapia',
  'Consulta de terapia ocupacional',
  'Consulta de fonoaudiologia',
  'Consulta de acupuntura',
  'Consulta de homeopatia',
  'Consulta de medicina integrativa',
  'Consulta de alergologia',
  'Consulta de imunologia',
  'Consulta de infectologia',
  'Consulta de hematologia',
  'Consulta de oncologia',
  'Consulta de cirurgia geral',
  'Consulta de cirurgia plástica',
  'Consulta de cirurgia vascular',
  'Consulta de cirurgia cardíaca',
  'Consulta de cirurgia torácica',
  'Consulta de cirurgia de cabeça e pescoço',
  'Consulta de cirurgia de coluna',
  'Consulta de cirurgia ortopédica',
  'Consulta de cirurgia pediátrica',
  'Consulta de cirurgia urológica',
  'Consulta de cirurgia ginecológica',
  'Consulta de cirurgia dermatológica',
  'Consulta de cirurgia bucomaxilofacial',
  'Consulta de cirurgia oftalmológica',
  'Consulta de cirurgia otorrinolaringológica',
  'Consulta de cirurgia neurológica',
  'Consulta de cirurgia oncológica',
  'Consulta de cirurgia bariátrica',
  'Consulta de cirurgia de transplante',
  'Consulta de cirurgia endoscópica',
  'Consulta de anestesiologia',
  'Consulta de medicina nuclear',
  'Consulta de radiologia',
  'Consulta de ultrassonografia',
  'Consulta de tomografia',
  'Consulta de ressonância magnética',
  'Consulta de densitometria óssea',
  'Consulta de mamografia',
  'Consulta de PET scan',
  'Consulta de cintilografia',
  'Consulta de eletrocardiograma',
  'Consulta de ecocardiograma',
  'Consulta de teste ergométrico',
  'Consulta de holter',
  'Consulta de MAPA',
  'Consulta de polissonografia',
  'Consulta de espirometria',
  'Consulta de endoscopia digestiva',
  'Consulta de colonoscopia',
  'Consulta de retossigmoidoscopia',
  'Consulta de broncoscopia',
  'Consulta de cistoscopia',
  'Consulta de histeroscopia',
  'Consulta de laparoscopia',
  'Consulta de artroscopia',
  'Consulta de videolaparoscopia',
  'Consulta de videoartroscopia',
  'Consulta de pHmetria',
  'Consulta de manometria',
  'Consulta de urodinâmica',
  'Consulta de eletromiografia',
  'Consulta de biópsia de pele',
  'Consulta de biópsia de fígado',
  'Consulta de biópsia de rim',
  'Consulta de biópsia de pulmão',
  'Consulta de biópsia de mama',
  'Consulta de biópsia de próstata',
  'Consulta de biópsia de medula óssea',
  'Consulta de biópsia de gânglios linfáticos',
  'Consulta de biópsia de tireoide',
  'Consulta de biópsia de pâncreas',
  'Consulta de biópsia de intestino',
  'Consulta de biópsia de estômago',
  'Consulta de biópsia de bexiga',
  'Consulta de biópsia de útero',
  'Consulta de biópsia de ovário',
  'Consulta de biópsia de testículo',
  'Consulta de biópsia de tecido mole',
  'Consulta de biópsia óssea',
  'Consulta de vacinação',
  'Consulta de planejamento familiar',
  'Consulta de pré-natal',
  'Consulta de puericultura',
  'Consulta de avaliação pré-operatória',
  'Consulta de seguimento pós-operatório',
  'Consulta de check-up',
  'Consulta de avaliação de risco cardiovascular',
  'Consulta de controle de diabetes',
  'Consulta de controle de hipertensão',
  'Consulta de controle de colesterol',
  'Consulta de controle de obesidade',
  'Consulta de controle de osteoporose',
  'Consulta de controle de asma',
  'Consulta de controle de DPOC',
  'Consulta de controle de epilepsia',
  'Consulta de controle de doenças autoimunes',
  'Consulta de controle de doenças reumatológicas',
  'Consulta de controle de doenças infecciosas',
  'Consulta de controle de doenças renais',
  'Consulta de controle de doenças hepáticas',
  'Consulta de controle de doenças gastrointestinais',
  'Consulta de controle de doenças hematológicas',
  'Consulta de controle de doenças oncológicas',
  'Consulta de controle de doenças cardiovasculares',
  'Consulta de controle de doenças neurológicas',
  'Consulta de controle de doenças psiquiátricas',
  'Consulta de controle de doenças respiratórias',
  'Consulta de controle de doenças dermatológicas',
  'Consulta de controle de doenças endócrinas',
  'Consulta de controle de doenças oftalmológicas',
  'Consulta de controle de doenças otorrinolaringológicas',
  'Consulta de controle de doenças genéticas',
  'Consulta de controle de doenças metabólicas',
  'Consulta de controle de doenças imunológicas',
  'Consulta de controle de doenças alérgicas',
  'Consulta de controle de doenças profissionais',
  'Consulta de controle de doenças do trabalho',
  'Consulta de controle de doenças tropicais',
  'Consulta de controle de doenças parasitárias',
  'Consulta de controle de doenças sexualmente transmissíveis',
  'Consulta de controle de saúde mental',
  'Consulta de controle de saúde reprodutiva',
  'Consulta de controle de saúde do adolescente',
  'Consulta de controle de saúde do idoso',
  'Consulta de controle de saúde da mulher',
  'Consulta de controle de saúde do homem',
  'Consulta de controle de saúde da criança',
  'Consulta de controle de saúde do recém-nascido',
  'Consulta de controle de saúde do trabalhador',
  'Consulta de controle de saúde ambiental',
  'Consulta de controle de saúde comunitária',
  'Consulta de controle de saúde pública',
  'Consulta de controle de saúde escolar',
  'Consulta de controle de saúde ocupacional',
  'Consulta de controle de saúde rural',
  'Consulta de controle de saúde urbana',
  'Consulta de controle de saúde domiciliar',
  'Consulta de controle de saúde hospitalar',
  'Consulta de controle de saúde ambulatorial',
  'Consulta de controle de saúde emergencial',
  'Consulta de controle de saúde de viagem',
  'Consulta de controle de saúde pré-embarque',
  'Consulta de controle de saúde pós-embarque',
  'Consulta de controle de saúde do atleta',
  'Consulta de controle de saúde do motorista',
  'Consulta de controle de saúde do piloto',
  'Consulta de controle de saúde do mergulhador',
  'Consulta de controle de saúde do trabalhador rural',
  'Consulta de controle de saúde do trabalhador industrial',
  'Consulta de controle de saúde do trabalhador da construção civil',
  'Consulta de controle de saúde do trabalhador do setor de serviços',
  'Consulta de controle de saúde do trabalhador da área da saúde',
  'Consulta de controle de saúde do trabalhador da área de educação',
  'Consulta de controle de saúde do trabalhador da área de segurança',
  'Consulta de controle de saúde do trabalhador da área de tecnologia',
  'Consulta de controle de saúde do trabalhador da área de transporte',
  'Consulta de controle de saúde do trabalhador da área de alimentação',
  'Consulta de controle de saúde do trabalhador da área de comércio',
  'Consulta de controle de saúde do trabalhador da área de entretenimento',
  'Consulta de controle de saúde do trabalhador da área de turismo',
  'Consulta de controle de saúde do trabalhador da área de agricultura',
  'Consulta de controle de saúde do trabalhador da área de pecuária',
  'Consulta de controle de saúde do trabalhador da área de pesca',
  'Consulta de controle de saúde do trabalhador da área de mineração',
  'Consulta de controle de saúde do trabalhador da área de energia',
  'Consulta de controle de saúde do trabalhador da área de meio ambiente',
  'Consulta de controle de saúde do trabalhador da área de saneamento',
  'Consulta de controle de saúde do trabalhador da área de telecomunicações',
  'Consulta de controle de saúde do trabalhador da área de logística',
  'Consulta de controle de saúde do trabalhador da área de finanças',
  'Consulta de controle de saúde do trabalhador da área de administração',
  'Consulta de controle de saúde do trabalhador da área de marketing',
  'Consulta de controle de saúde do trabalhador da área de publicidade',
  'Consulta de controle de saúde do trabalhador da área de design',
  'Consulta de controle de saúde do trabalhador da área de engenharia',
  'Consulta de controle de saúde do trabalhador da área de arquitetura',
  'Consulta de controle de saúde do trabalhador da área de direito'

];
